import type { Metadata } from "next";
import "./globals.css";
import "./index.css";
import { Creepster, Henny_Penny, Raleway, Ubuntu, Nosifer, Are_You_Serious, Kablammo, Griffy, Lacquer } from "next/font/google";
import Navbar from "./components/Navbar";

// Define each font
const creepster = Creepster({ weight: "400", subsets: ["latin"], variable: "--font-creepster" });
const hennyPenny = Henny_Penny({ weight: "400", subsets: ["latin"], variable: "--font-henny-penny" });
const raleway = Raleway({ weight: "400", subsets: ["latin"], variable: "--font-raleway" });
const ubuntu = Ubuntu({ weight: "400", subsets: ["latin"], variable: "--font-ubuntu" });
const nosifer = Nosifer({ weight: "400", subsets: ["latin"], variable: "--font-nosifer" });
const areYouSerious = Are_You_Serious({ weight: "400", subsets: ["latin"], variable: "--font-serious" });
const kablammo = Kablammo({ weight: "400", subsets: ["latin"], variable: "--font-kablammo" });
const griffy = Griffy({ weight: "400", subsets: ["latin"], variable: "--font-griffy" });
const lacquer = Lacquer({ weight: "400", subsets: ["latin"], variable: "--font-lacquer" });

// You mentioned Bitcount & SUSE Mono – those are *not* available in next/font/google*
// you can include them via @import in CSS if needed.

export const metadata: Metadata = {
  title: "Ghouls_night",
  description: "Generated by ghouls",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`
        ${creepster.variable}
        ${hennyPenny.variable}
        ${raleway.variable}
        ${ubuntu.variable}
        ${nosifer.variable}
        ${areYouSerious.variable}
        ${kablammo.variable}
        ${griffy.variable}
        ${lacquer.variable}
      `}>
      <body
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
